version: '2'
services:
  phoneticapi:
    build: 
      "./phoneticapi"
    ports:
      - "8000:8000"
  phoneticfrontend:
    build:
      "./phoneticapi-frontend"
    links:
      - phoneticapi:phoneticapi
    ports:
      - "8082:80"

