version: '2'
services:
  phoneticapi:
    build: 
      "./phoneticapi"
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  phoneticfrontend:
    build:
      "./phoneticapi-frontend"
    links:
      - phoneticapi:phoneticapi
    ports:
      - "8082:80"
  db:
    image: postgres:15.4
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD", "bash", "-c", 'if [ -s "$PGDATA/PG_VERSION" ]; then echo 1; fi ']
      interval: 10s

